apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx
spec:
  containers:
    - name: web
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: pod2-config
