apiVersion: v1
kind: Pod
metadata:
  name: test-ubuntu
  labels:
    role: test-ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:24.04
      command:
        - sleep
        - infinity
